options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/hackathon-backend'
      - '-f'
      - 'development/back/Dockerfile'
      - 'development/back'


  # Cloud Run deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - hackathon-backend
      - '--image'
      - 'gcr.io/$PROJECT_ID/hackathon-backend'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/hackathon-backend'
