CREATE TABLE IF NOT EXISTS user_revenues (
    uid VARCHAR(128) NOT NULL PRIMARY KEY,
    revenue_cents BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
